genprog:
  program: "repair"
  path: "/home/epicosy/thesis/implementation/repair/SecureThemAll/repair_tools/genprog-code/src"
  args:
    --search: "ga"
    --crossover: "subset"
    --describe-machine: ""
    --minimization: ""
    --seed: "0"
    --rep-cache: "default.cache"
    --ignore-dead-code: ""
    --no-rep-cache: ""
    --keep-source: ""
    --swapp: "0.0"
    --appp: "0.5"
    --delp: "0.5"
    --crossp: "0.0"
    --popsize: "20"
    --generations: "10"
    --allow-coverage-fail: ""
  sanity_check: true
  fault_localization: true
  container: genprog

